name: Dev-Coach
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - run: npm install
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          DATABASE_DEV: ${{ secrets.DATABASE_DEV }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_TEST: ${{ secrets.DATABASE_TEST }}
          SECRET: ${{ secrets.SECRET }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATEREPORTERID }}
        with:
          coverageCommand: npm run coverage
          coverageLocations: "./coverage/clover.xml:clover"
          debug: true